### ISSUE TITLE
center environment is considered bad style for figures

### ISSUE THREAD

**Issue by michaelaye** [rbeyer/lpsc_template#1]
Following this discussion here:

https://tex.stackexchange.com/questions/2651/should-i-use-center-or-centering-for-figures-and-tables

it is recommended to use `\centering` for images instead of the `center` environment, because it creates, usually unwanted, additional vertical space.

You might have hacked that extra space away already in your style file, but I thought I let you know nonetheless.

**Comment by rbeyer** [comment]
Thanks, Michael, I wasn't aware.  I've changed the template to \centering.  Thanks!

**Comment by michaelaye** [comment]
yeah, lot's of Tex Snippet editors have spread this style, unfortunately. Thanks for your and Moses' templates, they are great!
